### ISSUE TITLE
Build hangs unexpectedly at various times while running transforms

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-obo#102]
### Describe the bug

As of Jenkins build 65, the build hangs with no further output or errors upon reaching this point:
```
...
17:43:17  Looking for kg-obo/fao/index.html
17:43:17  Found kg-obo/fao/index.html
17:43:17  Looking for kg-obo/hso/index.html
17:43:17  Found kg-obo/hso/index.html
17:43:17  Looking for kg-obo/cmo/index.html
17:43:17  Found kg-obo/cmo/index.html
17:43:17  Refreshed root index at kg-obo
```
The corresponding point in `transform.py` is:
https://github.com/Knowledge-Graph-Hub/kg-obo/blob/0fa12506729d44e498455294263d348f35c42a92/kg_obo/transform.py#L516-L535

### To Reproduce

Run the following on Jenkins, on the main branch:
```
python3.8 run.py --bucket kg-hub-public-data --no_dl_progress --force_index_refresh --robot_path /var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/venv/bin/robot
```

## Expected behavior

The next output should resemble the following:
```
processing ontologies:   0%|                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
bfo
http://purl.obolibrary.org/obo/bfo.owl
```

### Version

12fbcc79368f51b6d16959b0b0c3ce0c9be32bc8

### Additional context

An identical run with the `--s3_test` option on appears to run as expected.

**Comment by justaddcoffee** [comment]
Ah okay, interesting. Possibly there was a high load on that machine earlier when it was hanging? (May be related to the problem with zombies that @kltm noticed the other day)

**Comment by caufieldjh** [comment]
May also make sense to install/run ROBOT from a different location - right now it's run from `/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/venv/bin/`

**Comment by kltm** [comment]
I can't prove anything, but having a hardcoded path to the host filesystem in a directory that (I believe) gets occasionally destroyed might cause weirdness in some cases. I might suggest using a `$WORKSPACE` variable like https://github.com/geneontology/pipeline/blob/386d830af5ec7f27f3d7e2bf091c0884030147e7/Jenkinsfile#L214 .
That said, I doubt that explains the zombies and the hanging.

**Comment by caufieldjh** [comment]
This may be an issue with the Python `subprocess` module itself, as it [has a fixed buffer size](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) and [can silently hang/deadlock when the buffer fills](https://stackoverflow.com/questions/39477003/python-subprocess-popen-hanging). 
So I suspect this isn't *explicitly* due to Jenkins, just creating conditions perfect for filling buffers of fixed size.

**Comment by caufieldjh** [comment]
On a test build (test_robot_run_jenkins, build 1) there was a long pause (> 3 hrs) at this point:
```
17:46:10  
processing ontologies:   1%|          | 1/193 [00:10<33:05, 10.34s/it]INFO:kg-obo:Loading chebi
17:46:12  INFO:kg-obo:Current VersionIRI for chebi: http://purl.obolibrary.org/obo/chebi/204/chebi.owl
17:46:12  INFO:kg-obo:Current version for chebi: 204
21:18:48  INFO:kg-obo:Transforming to tsv...
```
Several other transforms proceed as expected until reaching pr:
```
23:27:48  
processing ontologies:   4%|▎         | 7/193 [5:41:47<71:24:00, 1381.94s/it] INFO:kg-obo:Loading pr
23:27:49  INFO:kg-obo:Current VersionIRI for pr: http://purl.obolibrary.org/obo/pr/63.0/pr.owl
23:27:49  INFO:kg-obo:Current version for pr: 63.0
```
at which point it hangs (i.e, it's still at the same point > 10 hrs later).

This test branch doesn't read or write to/from S3, and a similar test build has completed without issue in the recent past.
ROBOT is running from the same location as the git repo:
```
17:46:01  ROBOT path: /var/lib/jenkins/workspace/ub_kg-obo_test_robot_run_jenkins/gitrepo/robot
```

Interestingly, the timeout I set on the call to ROBOT isn't working or is being ignored.

**Comment by caufieldjh** [comment]
Some of this hanging/slowness is alleviated by not doing a full diff between raw and ROBOT-processed OWLs. (see #112)
