### ISSUE TITLE
A few graphs are currently in 404

### ISSUE THREAD

**Issue by LucaCappelletti94** [Knowledge-Graph-Hub/kg-obo#107]
The following graphs are currently in 404:

- [oba](https://kg-hub.berkeleybop.io/kg-obo/oba/)
- [ehdaa2](https://kg-hub.berkeleybop.io/kg-obo/ehdaa2/)
- [aeo](https://kg-hub.berkeleybop.io/kg-obo/aeo/)
- [idomal](https://kg-hub.berkeleybop.io/kg-obo/idomal/)
- [pr](https://kg-hub.berkeleybop.io/kg-obo/pr/)
- [miro](https://kg-hub.berkeleybop.io/kg-obo/miro/)
- [tads](https://kg-hub.berkeleybop.io/kg-obo/tads/)
- [mod](https://kg-hub.berkeleybop.io/kg-obo/mod/)
- [tgma](https://kg-hub.berkeleybop.io/kg-obo/tgma/)
- [vt](https://kg-hub.berkeleybop.io/kg-obo/vt/)
- [tto](https://kg-hub.berkeleybop.io/kg-obo/tto/)
- [aro](https://kg-hub.berkeleybop.io/kg-obo/aro/)
- [hom](https://kg-hub.berkeleybop.io/kg-obo/hom/)

**Comment by caufieldjh** [comment]
Reopening so I remember to verify these are accessible upon new build

**Comment by caufieldjh** [comment]
Haven't run a fresh production build due to finding another major bug during testing. Will let you know once it's live!

**Comment by caufieldjh** [comment]
Closing as these are all online now, with the exception of `miro` which has some transformation issues.
