### ISSUE TITLE
Graphs with maximum degree 1

### ISSUE THREAD

**Issue by LucaCappelletti94** [Knowledge-Graph-Hub/kg-obo#108]
The following graphs have a significant number of nodes and just a single edge:

- [planp](https://kg-hub.berkeleybop.io/kg-obo/planp)
- [cdno](https://kg-hub.berkeleybop.io/kg-obo/cdno)
- [zp](https://kg-hub.berkeleybop.io/kg-obo/zp)
- [xpo](https://kg-hub.berkeleybop.io/kg-obo/xpo)

​

**Comment by caufieldjh** [comment]
In the case of `cdno`, this appears to be due to the base version containing virtually nothing. Weird!
Compare
https://raw.githubusercontent.com/Southern-Cross-Plant-Science/cdno/master/cdno-base.owl
to
https://raw.githubusercontent.com/Southern-Cross-Plant-Science/cdno/master/cdno.owl

**Comment by caufieldjh** [comment]
These base OBOs are all entirely dependent upon reasoning, so their base files aren't useful on their own.
A "base plus" may help and would be preferable to including the full set of imports for each of these.

**Comment by caufieldjh** [comment]
The OBOs `cdno` and `zp` look correct now, but `planp` and `xpo` still have one edge.
```
Name    Version Format  LastModified    Size    Nodes   Edges   ConnectedComponents     Singletons      MaxNodeDegree   MeanNodeDegree
cdno    2021-10-20      TSV     2021-11-11 20:44:41+00:00       210830  1939    3123    (95, 1, 1796)   90      542     3.22
cdno    2021-10-20      JSON    2021-11-11 20:44:40+00:00       1274289 1939    3123    (95, 1, 1796)   90      542     3.22
planp   2020-03-28      TSV     2021-10-02 08:29:58+00:00       17481   1287    1       (1286, 1, 2)    1285    1       0.00
planp   2020-03-28      JSON    2021-10-02 08:29:58+00:00       480767  1287    1       (1286, 1, 2)    1285    1       0.00
xpo     2021-03-05      TSV     2021-10-02 09:10:27+00:00       442745  21898   1       (21897, 1, 2)   21896   1       0.00
xpo     2021-03-05      JSON    2021-10-02 09:10:26+00:00       9954497 21898   1       (21897, 1, 2)   21896   1       0.00
zp      2021-12-12      TSV     2021-12-14 23:36:17+00:00       8070744 97826   151382  (4021, 1, 72954)        4011    3937    3.09
zp      2021-12-12      JSON    2021-12-14 23:36:18+00:00       43560005        97826   151382  (4021, 1, 72954)        4011    3937    3.09
```
They may just need to be transformed from scratch - thought they were being updated properly but that may not have happened.

**Comment by caufieldjh** [comment]
The planp and xpo transforms will be refreshed in the next build.
