### ISSUE TITLE
Implement logging for KG-OBO artifacts

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-obo#136]
Independent of the KG-OBO code, but still very nice to know: how are KG-OBO transforms being used?
This may be done through S3 server access logging (https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html)

**Comment by caufieldjh** [comment]
See also https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html

**Comment by justaddcoffee** [comment]
@kltm I think we may need a new bucket for these logs to live in, perhaps called `s3://kg-hub-public-data_log` or some such. 

Could you make us a bucket? I don't think Harry or I have the juice

**Comment by kltm** [comment]
@justaddcoffee @caufieldjh See slack PM.

**Comment by kltm** [comment]
Noting here bucket is named `kg-hub-service-logs`.
As per the conversation in slack on 2021-11-30, you both now have logins to continue what your were planning. I'll further info to the slack.

**Comment by caufieldjh** [comment]
Server access logging is enabled. Thanks @kltm
