### ISSUE TITLE
Problematic graphs

### ISSUE THREAD

**Issue by LucaCappelletti94** [Knowledge-Graph-Hub/kg-obo#166]
### Describe the bug
The graphs listed below either have empty edge/node lists or have problematic URLs.

- [GEO](https://kg-hub.berkeleybop.io/kg-obo/geo/)
- [XLMOD](https://kg-hub.berkeleybop.io/kg-obo/xlmod/no_version/)
- [CVDO](https://kg-hub.berkeleybop.io/kg-obo/cvdo/2020-03-05/)
- [INO](https://kg-hub.berkeleybop.io/kg-obo/ino/)
- [KISAO](https://kg-hub.berkeleybop.io/kg-obo/kisao/)
- [ICEO](https://kg-hub.berkeleybop.io/kg-obo/iceo/)
- [EPSO](https://kg-hub.berkeleybop.io/kg-obo/epso/)

**Comment by caufieldjh** [comment]
DIDEO is also on this list.

These should all be fixed as of the next build.

**Comment by caufieldjh** [comment]
EPSO is actually EPIO (which is also on KG-OBO and more or less identical) so I'm going to remove EPSO.
