### ISSUE TITLE
Prevent multiple concurrent runs of pipeline

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-obo#22]
We want to prevent multiple concurrent runs of the pipeline. This would cause these runs to all be writing to the s3 bucket at the same time and writing mutually inconsistent data.

This problem may result for example from multiple PRs being merged in quick succession, since Jenkins starts a new run when it sees a new commit to main.

### Describe the desired behavior

Any run of the pipeline should check whether there is a currently running pipeline, and if so, it should fail. 

One way of accomplishing this might be for `run.py` to look for a file at, say:

`s3_bucket/kg-obo/locked`

and if it exists, die. If this file doesn't exist, write this file to the s3c and continue with pipeline, then remove this file. (Other better ideas welcome.)

**Comment by caufieldjh** [comment]
Handled in #25
