### ISSUE TITLE
Skip transform for ontology versions for which we already have done a transform

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-obo#24]
### Describe the desired behavior

When looping through ontologies, skip those for which we already have transforms. PR #17 added code to extract version info, but IIUC we aren't check whether we've transformed and uploaded the version in question yet.

**Comment by caufieldjh** [comment]
Great, this one's next up.
Should be able to take care of #7 and #22 in the process.

**Comment by justaddcoffee** [comment]
Seems to work correctly in #25 - we can probably close this ticket when this PR is merged
