### ISSUE TITLE
lock file should be checked for on target s3 bucket, not locally

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-obo#31]
### Describe the bug

Right now we are checking for a `lock` file before we proceed with a kg-obo run, see [here](https://github.com/Knowledge-Graph-Hub/kg-obo/blob/eda7f2c7e17aebe527c46b329abeaec67bb426fa/run.py#L35). This prevents two runs of kg-obo at the same time on the same machine, but two separate runs will can and will still proceed on separate machines. 

This will be a problem: in Jenkins multiple runs will be started when several PRs are merged in quick succession, and these will all run at the same time and possibly upload at the same time to the same S3 bucket, which will be a mess.

### To Reproduce

`python run.py --get_only bfo # for example`

## Expected behavior

I'd suggest that we instead look for a file named `lock` on the target S3 bucket, and if it exists, die. If it doesn't exist, create it on the S3 bucket and proceed with transform, then delete it after the run is finished. (We'll need to invalidate the cache too so it really doesn't show up when the next transform starts.)

### Version

46a876824b5a2a6809bdd65a6f67d82987321301

**Comment by caufieldjh** [comment]
Addessed in #32.
