### ISSUE TITLE
Use KGX to convert OWL -> KGX TSV (to remove robot requirement)

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-obo#4]
@caufieldjh could/should we use Deepak's KGX fix [here](https://github.com/deepakunni3/kgx/tree/issue-329) and just use KGX to convert OWL -> KGX TSV? 

Seems like this would simplify the code a lot, and we could maybe help KGX support this conversion better - what do you think?

**Comment by caufieldjh** [comment]
Yes, absolutely. I'd like to do this on a new branch though, to have robot as a fallback. I don't anticipate there being any major issues regarding OWL to TSV transforms but I'd like to keep an eye on any missing edges etc.

**Comment by caufieldjh** [comment]
It actually looks like kgx won't do JSON -> TSV alone anyway (https://github.com/biolink/kgx/issues/332) without further fixes, so I'm happy to just remove robot entirely.

**Comment by justaddcoffee** [comment]
Okay, sounds like a plan

**Comment by caufieldjh** [comment]
Done
