### ISSUE TITLE
Lock file not removed when run fails

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-obo#43]
### Describe the bug

When a run fails due to a runtime error, the lock file persists. See [this run](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-obo/job/main/22), which failed due to a runtime error, and [this subsequent run](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-obo/job/main/23), which fails because the lock file is still there.

### To Reproduce

See above

## Expected behavior

We should maybe catch runtime errors in `run_transform` (that are NOT due to the presence of a lock file), and remove the lock file

### Version

21e4d9a

**Comment by justaddcoffee** [comment]
sub-issue - [this](https://github.com/Knowledge-Graph-Hub/kg-obo/blob/21e4d9a32f1d760d25f9e25ac916662ed57342ab/kg_obo/transform.py#L256) could maybe be `sys.exit(0)` - right now Jenkins thinks this is a run failure when a lock exists, which arguably it isn't

**Comment by caufieldjh** [comment]
See #45
