### ISSUE TITLE
Transforms for which KGX reports errors and warnings are still uploaded to s3

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-obo#47]
### Describe the bug

Transforms for which KGX reports errors and warnings are still uploaded to s3 - for example DOID
```
~ $ s3cmd ls s3://kg-hub-public-data/kg-obo/doid/2021-08-17/
2021-09-14 21:19      1494347  s3://kg-hub-public-data/kg-obo/doid/2021-08-17/doid.tar.gz
```
## Expected behavior

Should not upload transformed ontologies when there is an error or warning

### Version

https://github.com/Knowledge-Graph-Hub/kg-obo/commit/5652f3391d4d5a80a1e09c02e0f1a3180e71cb75

**Comment by caufieldjh** [comment]
See #48

**Comment by justaddcoffee** [comment]
Seems to be fixed
