### ISSUE TITLE
When version of ontology isn't found in OWL, transform code thinks it has been transformed already

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-obo#50]
### Describe the bug

If version info isn't found in OWL, version is set to "NA", which makes sense. When the code then checks `tracking.yaml`, if the ontology hasn't been transformed already, it sees `NA`, and thinks this "version" has already been transformed.

Example is aro: 

```
processing ontologies:   8%|▊         | 16/193 [1:32:59<3:34:37, 72.75s/it] INFO:kg-obo:Loading aro
21:11:06  aro
21:11:06  http://purl.obolibrary.org/obo/aro.owl
21:11:06  
21:11:06  
  0%|          | 0.00/358k [00:00<?, ?B/s][A
7.05MB [00:00, 135MB/s]                   
21:11:06  INFO:kg-obo:Current VersionIRI for aro: NA
21:11:07  INFO:kg-obo:Have already transformed aro: NA
```

### To Reproduce

See [here](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-obo/job/main/31/consoleFull)

## Expected behavior

We should differentiate between `NA` that means "couldn't find a version" (which is what `get_owl_iri ` means by `NA`) and `NA` that means "this hasn't been transformed yet (which is what `tracking.yaml` means by `NA`).

Simple fix would be for `get_owl_iri` to return something other than `NA` when it can't find a version. Say, "unknown_version", or the ontology name, or a timestamp. 

(nb: a timestamp would mean a new version would be created in kg-obo on every pipeline runs, which might be okay)

### Version

3a24fdb

**Comment by caufieldjh** [comment]
Will address by using other values from OWL header as fallback.

**Comment by caufieldjh** [comment]
See #53

**Comment by caufieldjh** [comment]
See also #59
