### ISSUE TITLE
FAO version not parsed as expected

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-obo#58]
### Describe the bug

The OBO [fao](http://www.obofoundry.org/ontology/fao.html) has a *slightly* different IRI structure from most, causing its version to be parsed incorrectly.

### To Reproduce

`$ python3 run.py --s3_test --bucket kg-obo --get_only fao`
Output will be in 'data/fao/fao/' rather than 'data/fao/2020-05-07/'.

In the tracking.yaml, the relevant lines are:
```
  fao:
    current_iri: http://purl.obolibrary.org/obo/fao/releases/2020-05-07/fao/fao-base.owl
    current_version: fao
```

Compare to bfo:
```
  bfo:
    current_iri: http://purl.obolibrary.org/obo/bfo/2019-08-26/bfo.owl
    current_version: '2019-08-26'
```

## Expected behavior

The version for fao should be '2020-05-07'.

**Comment by justaddcoffee** [comment]
This bug or something similar is causing the pipeline to fail when transforming aro I think - see [here](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-obo/job/main/35/console):

```
15:02:00  aro
15:02:00  http://purl.obolibrary.org/obo/aro.owl
15:02:00  
15:02:00  
  0%|          | 0.00/358k [00:00<?, ?B/s][A
7.05MB [00:00, 139MB/s]                   
15:02:00  INFO:kg-obo:Current VersionIRI for aro: 05:07:2021 15:21</oboInOwl:date>
15:02:01  
processing ontologies:   8%|▊         | 16/193 [1:34:54<17:29:57, 355.92s/it]
15:02:01  Version IRI not found.
15:02:01  Current VersionIRI for aro: 05:07:2021 15:21</oboInOwl:date>
15:02:01  [Errno 2] No such file or directory: 'data/aro/05:07:2021 15:21</oboInOwl:date>'
15:02:01  Removing lock due to error...
15:02:01  deleting lock file s3_bucket:kg-hub-public-data, s3_path:kg-obo/lock
15:02:01  Lock removed.
```

Also, I think `run.py` should be returning an error in this case so that Jenkins knows that it failed...

**Comment by caufieldjh** [comment]
I suspect both of these are special cases causing some kind of regex failure. Might just need to hardcode parsing these IRIs.

**Comment by justaddcoffee** [comment]
The version info being parsed in aro.owl is:

```
        <oboInOwl:date rdf:datatype="http://www.w3.org/2001/XMLSchema#string">05:07:2021 15:21</oboInOwl:date>
```

so yeah, probably a regex failure. 

Not sure what you mean by hardcoding parsing these IRIs?
